language: php

php:
    - 7.0
    - 7.1.3
    - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - mkdir -p ./build/logs
    - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

after_success:
- travis_retry php vendor/bin/php-coveralls -v